name: fasdoor pvt ltd.

on:
  push:
    branches:
      - main
      - feature/aniruddha-26-10-2024/implement-github-actions

jobs:
  build-deploy:
    name: Build And Deploy Fasdoor Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Unit Test
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml